---

- name: Use handlers to take care of business
  hosts: robots

  tasks:
      - name: Use ping
        ping:
        notify: reping
        changed_when: true # Use this option to automatically mark this changed.



  handlers:
      - name: reping
        debug:
            msg: in reping

