<?xml version="1.0"?>

<!--
xacro file for mounting a camera on top of the hokuyo laser for the pioneer
robot

-->

<robot xmlns:xacro="http://ros.org/wiki/xacro" >
    <xacro:include filename="$(find csl_robot_descriptions)/defs/materials.xacro"/>
    <xacro:property name="camera_size" value="0.05" />

    <xacro:macro name="camera_macro" params="camera_name">

        <joint name="camera_joint" type="fixed">
            <axis xyz="0 1 0" />
            <parent link="hokuyo_link"/>
            <origin xyz="0 0 ${hokuyo_size/2}" rpy="0 0 0"/>
            <child link="camera_link"/>
        </joint>

        <!-- Camera -->
        <link name="camera_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${camera_size} ${camera_size} ${camera_size}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${camera_size} ${camera_size} ${camera_size}"/>
                </geometry>
                <material name="blue"/>
            </visual>

            <inertial>
                <mass value="1e-5" />
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
        </link>
	    <gazebo reference="camera_link">
		    <material value="Gazebo/Blue"/>
	    </gazebo>

        <!-- camera_link -->
        <gazebo reference="camera_link">
            <mu1>0.2</mu1>
            <mu2>0.2</mu2>
            <material>Gazebo/Red</material>
        </gazebo>


        <gazebo reference="camera_link">
            <sensor type="camera" name="camera1">
                <update_rate>30.0</update_rate>
                <camera name="head">
                    <horizontal_fov>1.3962634</horizontal_fov>
                    <image>
                        <width>800</width>
                        <height>800</height>
                        <format>R8G8B8</format>
                    </image>
                    <clip>
                        <near>0.02</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>

                <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>0.0</updateRate>
                    <cameraName>camera1</cameraName>
                    <imageTopicName>image_raw</imageTopicName>
                    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                    <frameName>camera_link</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                </plugin>

            </sensor>
        </gazebo>
    </xacro:macro>
</robot>
