<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" >
    <xacro:property name="hokuyo_size" value="0.1" />

    <xacro:macro name="hokuyo_laser">
        <joint name="hokuyo_joint" type="fixed">
            <axis xyz="0 1 0" />
            <origin xyz="0.0 0.0 ${hokuyo_size/4}" rpy="0 0 0"/>
            <parent link="top_plate"/>
            <child link="hokuyo_link"/>
        </joint>

        <!-- Hokuyo Laser -->
        <link name="hokuyo_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://csl_robot_descriptions/meshes/hokuyo.dae"/>
                </geometry>
                <material name="black"/>
            </visual>

            <inertial>
                <mass value="1e-5" />
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
        </link>
	    <gazebo reference="hokuyo_link">
		    <material value="Gazebo/Black"/>
	    </gazebo>

        <!-- Hokuyo Laser -->
        <gazebo reference="hokuyo_link">
            <sensor type="gpu_ray" name="head_hokuyo_sensor">
                <pose>0 0 0 0 0 0</pose>
                <visualize>true</visualize>
                <update_rate>40</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>720</samples>
                            <resolution>1</resolution>
                            <min_angle>${-pi/2}</min_angle>
                            <max_angle>${pi/2}</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.10</min>
                        <max>30.0</max>
                        <resolution>0.01</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <!--
                             Noise parameters based on published spec for
                             Hokuyo laser achieving "+-30mm" accuracy at range
                             < 10m.  A mean of 0.0m and stddev of 0.01m will
                             put 99.7% of samples within 0.03m of the true
                             reading.
                        -->
                        <mean>0.0</mean>
                        <!--<stddev>0.01</stddev>-->
                        <stddev>0.1</stddev>
                    </noise>
                </ray>
                <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
                    <topicName>input/laser_scan</topicName>
                    <frameName>hokuyo_link</frameName>
                </plugin>
            </sensor>
        </gazebo>

    </xacro:macro>
</robot>

