# Fri Nov 4 12:06:39 EET 2016, Nikos Koukis
#
# Instructions on how to use with youbot:
# Use wireless Logitech joystick
# - Have Mode "off"
# - Have right axes "pressed in" when you want to give any command
# - Left Axes <-> => Move left/right
#             ^
# - Left Axes |   => Move forward backwards
#             v
#
# - Right Axes <-> => Yaw turn left/right

axis_linear:
  x: 1 # Forward/Back
  y: 0 # Left/Right
scale_linear:
  x: 0.2
  y: 0.1
axis_angular:
  yaw: 3
scale_angular:
  yaw: 0.5

#enable_button: 10  # L1 shoulder button
#enable_turbo_button: 8  # L2 shoulder button
