axis_linear:
  x: 1 # Forward/Back
  y: 0 # Left/Right
scale_linear:
  x: 0.2
  y: 0.1
axis_angular:
  yaw: 2
scale_angular:
  yaw: 0.5

enable_button: 10  # L1 shoulder button
enable_turbo_button: 8  # L2 shoulder button
