# Fri Nov 4 12:06:39 EET 2016, Nikos Koukis
#
# Components tested
# - Robot: Youbot
# - Joystick: Logitech Wireless Gamepad F710
#
# - Left Axes <--> => Move left/right
#             ^
# - Left Axes |   => Move forward backwards
#             v
#
# - Right Axes <--> => Yaw turn left/right

axis_linear:
  x: 1 # Forward/Back
  y: 0 # Left/Right
scale_linear:
  x: 0.2
  y: 0.1
scale_linear_turbo:
  x: 0.5
  y: 0.4

axis_angular:
  yaw: 3
scale_angular:
  yaw: 0.5

enable_button: 2 # "X"
enable_turbo_button: 1  # "O" - change to -1 to disable
