# configuration has been tested online with the following:
#
# - Robot: Pioneer-2dx robot
# - Joystick: Digital Element, GM-400
# - Left Axes <--> => Yaw turn left/right
#             ^
# - Left Axes |   => Move forward backwards
#             v

axis_linear: 1
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 0
scale_angular: 0.4

enable_button: 8  # L2 shoulder button
enable_turbo_button: 10  # L1 shoulder button
